config/routes.rb
KillerFalt::Application.routes.draw do
  get "request/new/:game_id", to: 'request#new'
  post "request/create", to: 'request#create'

  namespace :admin do
    resources :players, only: [:show, :edit, :update] do
      member do
         get 'kill'
         get 'alive'
       end
    end
    resources :requests, only: [:edit, :update]
  end

  devise_for :admins
  devise_for :players

	resources :players do
		member do
			post 'kill'
			post 'admin_kill'
			post 'set_target'
      post 'revive'
		end
  end

  resources :games
  namespace :admin do
    resources :games
  end
  get '/edit_info', to: 'players#edit_info'
  get '/edit_admin_info', to: 'admins#edit_info'
  get '/print_players/:game_id', to: 'admin/games#print_list'
	resources :admins
  resources :events
  resources :cards

  root to: 'static_pages#home'
  get '/static_pages/home', to: 'static_pages#home'
	get '/rules', to: 'static_pages#rules'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessor :password_confirmation #, :start_time, :start_date, :end_time, :end_date
  has_and_belongs_to_many :admins
  has_and_belongs_to_many :players
  has_many :requests
  has_many :events

  has_attached_file :logo, styles: {medium: ['300x300', :jpg]},
                    url: "/system/logo/:hash.:extension", hash_secret: 'killerfiztehbymorodeer',
                    default_url: "/system/logo/:style/missing.jpg"

  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :name, :starts_at, :ends_at, presence: true

  def started?
    Time.now > starts_at
  end

  def ended?
    closed || Time.now > ends_at
  end

  def status
    if ended? then 'Завершена'
    elsif started? then 'Начата'
    else 'Ожидает начала'
    end
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_filter :authenticate_admin!
  def index
    @player = current_admin
    @games = @player.games
  end

  def new
    @game = Game.new
    @game.starts_at = Time.now
    @game.ends_at = Time.now + 7.days
  end

  def create
    @game = Game.create(game_params)
    if @game.password == @game.password_confirmation
      if @game.save
        @game.admins << current_admin
        redirect_to admin_game_path(@game)
      end
    end

  end

  def show
    @admin = current_admin
    @game = Game.find_by_id(params[:id])
    @requests = @game.requests.where status: 'pending'
    @players = @game.players
  end

  def edit
    @game = Game.find_by_id(params[:id])
  end

  def update
    @game = Game.find_by_id(params[:id])

    if params[:password] == params[:password_confirmation]
      if @game.update_attributes(game_params)
        redirect_to admin_game_path(@game)
      end
    else
      render 'edit'
    end

  end

  def print_list
    @game = Game.find(params[:game_id])
    @players = @game.players
    respond_to do |format|
      format.html
      format.pdf do
            pdf = PlayersPdf.new(@players, @game)
        send_data pdf.render, filename: "playerspdf.pdf",type:"application/pdf", disposition: "inline"
      end
    end
  end

  private
    def game_params
      params.require(:game).permit(:name,:starts_at,:ends_at,:password, :password_confirmation, :closed,
        :question1, :question2, :question3, :question4, :logo)
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_player!


  def new
    @game = Game.new
  end


  def index
    @games = Game.all
    @requested_games = current_player.requests.map &:game
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/admin/games/edit.haml
.row
	%h1 Редактирование игры

	=form_for  @game, url: admin_game_path do |f|
		=f.label :name, 'Название игры'
		=f.text_field :name, autofocus: true

		=f.label :password, 'Пароль для участия в игре'
		=f.text_field :password

		=f.label :password_confirmation, 'Подтверждение пароля'
		=f.text_field :password_confirmation

		=f.label :starts_at, 'Старт игры'
		=f.datetime_local_field :starts_at

		=f.label :ends_at, 'Финиш игры'
		=f.datetime_local_field :ends_at

		=f.label :closed, 'Закрыта'
		=f.check_box :closed

		=f.label :logo, 'Логотип для игры'
		=f.file_field :logo

		%p Вопросы для заявок на участие:

		- (1..4).each do |i|
			=f.label "question#{i}".to_sym, "Вопрос ##{i}"
			=f.text_field "question#{i}".to_sym


		=f.submit 'Обновить параметры игры', class:'button'

app/views/admin/games/index.haml
.row
	%h1 Список администрируемых вами игр
	-#=link_to 'Список для печати', print_players_path

- if @games.empty?
	.row#body
		%p
			Вы не являетесь админом ни одной из игр.
			%br
			Вас могут назначить админом уже существующей игры
			или вы можете
			=link_to 'Создать', new_admin_game_path
			новую игру
- else
	.row#body
		%table
			%thead
				%tr
					%th Игра
					%th Начало
					%th Окончание
					%th Статус
					%th
			%tbody
				- @games.each do |game|
					%tr
						%th= link_to game.name, admin_game_path(game)
						%th= l(game.starts_at, :format => :short)
						%th= l(game.ends_at, :format => :short)
						%th= game.status
						%th= link_to 'Изменить', edit_admin_game_path(game)
		=link_to 'Создать новую игру', new_admin_game_path

app/views/admin/games/new.haml
.row
	%h1 Cоздание новой игры

	=form_for  @game, url: admin_games_path do |f|
		=f.label :name, 'Название игры'
		=f.text_field :name, autofocus: true

		=f.label :password, 'Пароль для участия в игре'
		=f.text_field :password

		=f.label :password_confirmation, 'Подтверждение пароля'
		=f.text_field :password_confirmation

		=f.label :starts_at, 'Старт игры'
		=f.datetime_local_field :starts_at

		=f.label :ends_at, 'Финиш игры'
		=f.datetime_local_field :ends_at

		=f.label :logo, 'Логотип для игры'
		=f.file_field :logo

		%p Вопросы для заявок на участие:

		- (1..4).each do |i|
			=f.label "question#{i}".to_sym, "Вопрос ##{i}"
			=f.text_field "question#{i}".to_sym


		=f.submit 'Создать игру', class:'button'
	-#
	-#%ul
	-#-@players.each do |player|
	-#	%li
	-#		= player.full_name
	-#		= player.login
	-#		= player.temp_password

app/views/admin/games/show.haml
.row
	%h1
		Игра
		=@game.name

	.row
		-if @game.logo.present?
			%p=image_tag @game.logo.url
		%p=link_to 'Редактировать', edit_admin_game_path(@game)


		%p=link_to 'Список для печати', "/print_players/#{@game.id}.pdf"

	.row
		%p
			Старт игры:
			= l @game.starts_at, format: :short
		%p
			Конец игры:
			= l @game.ends_at, format: :short
		%p
			Статус:
			= @game.status
	.row
		- unless @game.started? || @game.closed
			%h4 Список заявок
			%table
				%thead
					%td Аватар
					%td Имя
					%td VK
					%td Обработать
				- @requests.each do |request|
					%td= image_tag request.player.avatar.url(:thumb)
					%td= request.player.full_name
					%td= link_to("VK",request.player.vklink) if request.player.vklink
					%td= link_to 'Обработать', edit_admin_request_path(request)


	.row
		%h4 Список участников
		%table
			%thead
				%tr
					%th Аватар
					%th Имя
					%th Статус
					%th Цель
			%tbody
				- @players.each do |player|
					%tr
						%td= image_tag player.avatar.url(:thumb)
						%td
							= link_to player.full_name, edit_admin_player_path(player)
							- if player.banned
								(БАН)
						%td
							= player.status
							(
							- if player.dead
								= link_to "Оживить", alive_admin_player_path(player)
							- else
								= link_to "Убить", kill_admin_player_path(player)
							)

						%td= player.target



=javascript_include_tag('https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js')
:javascript
	var app = angular.module('miptkiller',[])

	app.controller('PlayersIndexCtrl',function($scope){
		$scope.requests = #{@players.to_json(only:[:id,:dead],methods:[:full_name,:avatar_thumb,:killers_cards_count],
				include:{target: {only: [:id],methods:[:full_name]}})}
	})