config/routes.rb
KillerFalt::Application.routes.draw do
  get "request/new/:game_id", to: 'request#new'
  post "request/create", to: 'request#create'

  namespace :admin do
    resources :players, only: [:show, :edit, :update] do
      member do
         get 'kill'
         get 'alive'
       end
    end
    resources :requests, only: [:edit, :update]
  end

  devise_for :admins
  devise_for :players

	resources :players do
		member do
			post 'kill'
			post 'admin_kill'
			post 'set_target'
      post 'revive'
		end
  end

  resources :games
  namespace :admin do
    resources :games
  end
  get '/edit_info', to: 'players#edit_info'
  get '/edit_admin_info', to: 'admins#edit_info'
  get '/print_players/:game_id', to: 'admin/games#print_list'
	resources :admins
  resources :events
  resources :cards

  root to: 'static_pages#home'
  get '/static_pages/home', to: 'static_pages#home'
	get '/rules', to: 'static_pages#rules'

end

app/views/shared/_error_messages.haml
- if object.errors.any?
	#error_explanation
		.alert-box.alert
			The form contains
			=pluralize(object.errors.count, "error")
			%ul
				-object.errors.full_messages.each do |msg|
					%li
						*
						=msg

app/views/shared/_flash.haml
.row
	- flash.each do |key, value|
		= content_tag(:div, value, :class => "alert-box flash #{key}")

app/views/shared/_footer.haml
%footer
	Создание и поддержка сайта - Юрий Дынников, ФАЛТ

app/views/shared/_ga.haml
:javascript

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-44191088-3']);
	_gaq.push(['_setDomainName', 'miptkiller.morodeer.ru']);
	_gaq.push(['_setAllowLinker', true]);
	_gaq.push(['_trackPageview']);

	(function() {
	var ga = document.createElement('script'); ga.type = 'text/javascript';
	  ga.async = true;

	ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
	var s = document.getElementsByTagName('script')[0];
	  s.parentNode.insertBefore(ga, s);
	})();

app/views/shared/_header.haml
%header
	.contain-to-grid
		%nav.top-bar
			.left_side
				#logo
					= link_to 'Killer Game', root_path

			.right_side
				- if admin_signed_in?
					=link_to 'Games', admin_games_path
					=link_to 'Profile settings', edit_admin_info_path
					=link_to 'Logout', destroy_admin_session_path, method: :delete
				- elsif player_signed_in?
					=link_to 'Profile settings', edit_info_path
					=link_to 'Logout', destroy_player_session_path, method: :delete
				-else
					=link_to 'Log in as admin', new_admin_session_path
					=link_to 'Log in as player', new_player_session_path
					=link_to 'Register as admin', new_admin_path
					=link_to 'Register as player', new_player_path