config/routes.rb
KillerFalt::Application.routes.draw do
  get "request/new/:game_id", to: 'request#new'
  post "request/create", to: 'request#create'

  namespace :admin do
    resources :players, only: [:show, :edit, :update] do
      member do
         get 'kill'
         get 'alive'
       end
    end
    resources :requests, only: [:edit, :update]
  end

  devise_for :admins
  devise_for :players

	resources :players do
		member do
			post 'kill'
			post 'admin_kill'
			post 'set_target'
      post 'revive'
		end
  end

  resources :games
  namespace :admin do
    resources :games
  end
  get '/edit_info', to: 'players#edit_info'
  get '/edit_admin_info', to: 'admins#edit_info'
  get '/print_players/:game_id', to: 'admin/games#print_list'
	resources :admins
  resources :events
  resources :cards

  root to: 'static_pages#home'
  get '/static_pages/home', to: 'static_pages#home'
	get '/rules', to: 'static_pages#rules'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :game
	belongs_to :source, class_name: "Player", inverse_of: :source_events
	belongs_to :target, class_name: "Player", inverse_of: :target_events
	belongs_to :card, class_name: "Card"
	belongs_to :new_target, class_name: "Player", inverse_of: :new_target_events

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	#before_filter :authenticate_admin!
	def index
		@events = Event.where(event_type:'murder').reorder('created_at DESC').paginate(page: params[:page])
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.haml
#body
	.row

		.panel
			%p Игра окончена, всем спасибо!
		%h1 Убийства
		=foundation_paginate @events

		.panel
			%p Теперь по дефолту у нас обратный порядок убийств - последние идут первыми.
		%table
			%thead
				%td Время
				%td Убийца
				%td Жертва
				%td Карточек
				%td Новая цель
			-@events.each do |event|
				%tr
					%td= (event.created_at + 4.hours).to_formatted_s(:short)
					%td= link_to event.source.full_name, player_path(event.source)
					%td= link_to event.target.full_name, player_path(event.target)
					%td= event.card_count
					%td= link_to event.new_target.full_name, player_path(event.new_target)