config/routes.rb
KillerFalt::Application.routes.draw do
  get "request/new/:game_id", to: 'request#new'
  post "request/create", to: 'request#create'

  namespace :admin do
    resources :players, only: [:show, :edit, :update] do
      member do
         get 'kill'
         get 'alive'
       end
    end
    resources :requests, only: [:edit, :update]
  end

  devise_for :admins
  devise_for :players

	resources :players do
		member do
			post 'kill'
			post 'admin_kill'
			post 'set_target'
      post 'revive'
		end
  end

  resources :games
  namespace :admin do
    resources :games
  end
  get '/edit_info', to: 'players#edit_info'
  get '/edit_admin_info', to: 'admins#edit_info'
  get '/print_players/:game_id', to: 'admin/games#print_list'
	resources :admins
  resources :events
  resources :cards

  root to: 'static_pages#home'
  get '/static_pages/home', to: 'static_pages#home'
	get '/rules', to: 'static_pages#rules'

end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  #before_validation :create_login_and_password
  devise :database_authenticatable,
         #:registerable,
         #:recoverable,
         :rememberable,
         :trackable,:validatable
  has_and_belongs_to_many :games

  has_many :killers_cards, class_name: "Card", foreign_key: :owner_id, dependent: :destroy
  has_one :victims_card, class_name: "Card", foreign_key: :victim_id, dependent: :destroy


  has_many :victims, through: :killers_cards
  has_one :killer, through: :victims_card

  has_many :source_events, class_name: 'Event', foreign_key: 'source_id'
  has_many :target_events, class_name: 'Event', foreign_key: 'target_id'
  has_many :new_target_events, class_name: 'Event', foreign_key: 'new_target_id'

  has_attached_file :avatar, styles: {medium: ['450x300', :jpg], thumb: ['150x100#', :jpg], small: ['32x32#', :jpg]},
                    url: "/system/avatars/:hash.:extension", hash_secret: 'killerfiztehbymorodeer',
                    default_url: "/system/avatars/:style/missing.jpg"

  has_many :requests

  belongs_to :target, class_name: 'Player'

  before_create do |player|
    player.build_victims_card owner: player
  end

  def die
		self.update_attribute(:dead,true)
  end

	def kill(player,password,method)
		if player.killing_word == password && self.target.id == player.id
			player.die
			player.victims_card.kill if player.victims_card
			player.killers_cards.each do |card|
				Event.create(event_type:'card_transfer',source:self,target:player,card:card,method:method)
			end
			killers_cards << player.killers_cards
			Event.create(event_type:'murder',source:self,target:player,method:method, new_target: self.target, card_count: self.killers_cards.count)
		end
	end

	def full_name
		"#{name} #{surname}"
	end

  def email_required?
		false
  end

  def email_changed?
		false
  end

  def update_killing_word
	  self.killing_word = SecureRandom.base64(6)
	  self.save
  end

  def update_login_and_password
	  self.login = (0..8).map{ ('a'..'z').to_a[rand(26)]}.join
	  self.password = (0..8).map{ ('a'..'z').to_a[rand(26)]}.join
	  self.password_confirmation = self.password
	  self.temp_password = self.password
		self.save
  end

  def avatar_thumb
    avatar.url(:thumb)
  end

  def killers_cards_count
    killers_cards.count
  end

  def current_game
    games.where("starts_at < ? AND ends_at > ?", Time.now, Time.now).first
  end

  def upcoming_game
    games.where("starts_at > ?", Time.now).first
  end

  def status
    dead ? "Убит" : "Жив"
  end
	#private
	#	def create_login_and_password
   #   if self.login == ""
  #
   #     self.login = (0..8).map{ ('a'..'z').to_a[rand(26)]}.join
   #     self.password = (0..8).map{ ('a'..'z').to_a[rand(26)]}.join
   #     self.password_confirmation = self.password
   #     self.temp_password = self.password
  	#		self.killing_word = SecureRandom.base64(6)
   #   end
  #
   #   #self.save
	#	end

  def to_s
    full_name
  end

end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :kill, :alive]
  before_filter :authenticate_admin!

  def show
    respond_with(@player)
  end

  def edit
    @possible_targets = game.players.where(dead: false).where.not(id: @player.id)
  end

  def update
    @player.update(player_params)
    redirect_to admin_game_path(game)
  end

  def kill
    @player.update dead: true
    redirect_to admin_game_path(game)
  end

  def alive
    @player.update dead: false
    redirect_to admin_game_path(game)
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:dead, :killing_word, :banned, :ban_reason, :target_id)
    end

    def game
      @player.current_game || @player.upcoming_game
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	#before_filter :authenticate_admin!, only: [:new, :create, :destroy, :show, :index, :admin_kill, :edit,
  # :print_list, :set_target]
  before_filter :authenticate_admin!, only: [:index, :edit]
	before_filter :authenticate_player!, except: [:new, :create]
  #before_filter :stop_game, except: [:show, :index]

	def new
		@player = Player.new
		@players = Player.all
	end

	def create
		@player = Player.create(params.require(:player).permit(:name,:surname,:email,:password, :password_confirmation, :vklink))
		if @player.save
      redirect_to root_path
		else
			render 'new'
		end
	end

	def destroy
		@player = Player.find_by_id(params[:id])
		@player.destroy
    redirect_to root_path
	end

	def index
		#@players = Player.paginate(page:params[:page])
		@players = Player.all
	end

	def edit_info
		@player = current_player
	end

	def edit
		@player = Player.find_by_id(params[:id])
	end

	def update    
		if admin_signed_in?
			@player = Player.find_by_id(params[:player][:id])
			if @player.update_attributes(player_params)
				redirect_to edit_player_path(@player), success: 'Параметры обновлены'
			else
				render 'edit'
			end
		elsif player_signed_in? and current_player.id.to_i == params[:player][:id].to_i
			@player = Player.find_by_id(params[:player][:id])

      if @player.current_game && @player.current_game.avatar_changeable
        permitparams = player_params_with_avatar
      else
        permitparams = player_params
      end

			if @player.update_attributes(permitparams)
				redirect_to new_player_session_path, success: 'Параметры обновлены'
			else
				render 'edit_info'
			end
		else
			redirect_to root_path, alert: 'У вас на это нет прав'
		end


	end

	def kill
		@target = Player.find_by_id(  params[:target][:id])
		@player = current_player
		if @player.target.id == @target.id
			puts 'starting killing'
			if @player.kill(@target,params[:target][:killing_word],'web')
				redirect_to root_path, success: 'Трупов всё больше, спасибо вам! )'
			else
				redirect_to root_path, alert: 'Промахнулись с жертвой или паролем. Брутфорс запрещен'
			end
		else
			redirect_to root_path, alert: 'У вас нет на это прав'
		end
	end

	def admin_kill
		@target = Player.find_by_id(params[:target][:id])
		@player = Player.find_by_id(params[:player][:id])
		if @player.target.id == @target.id
			puts 'starting killing'
			if @player.kill(@target,params[:target][:killing_word],'admin')
				redirect_to player_path(@player), success: 'Ок, убили.'
			else
				redirect_to player_path(@player), alert: 'С паролем не промахивайтесь =)'
			end
		end
	end

	def show
		@player = Player.find_by_id(params[:id])
		@target = @player.target
		@events = Event.where(event_type:'murder',source_id:@player.id)
		@killers_card = Card.where(owner: @player, victim: @target)
	end

	def set_target
		@player = Player.find_by_id(params[:id])
		@target = Player.find_by_id(params[:player][:id])
			Card.create(victim: @target, owner: @player)
		redirect_to @player
  end

  def revive
    @player = Player.find_by_id(params[:id])
    if @player.update_attributes(dead:nil)
      redirect_to @player
    else
      render 'show'
    end
  end

	private
		def is_current_player
			authenticate_player!
			unless params[:id].to_i == current_player.id.to_i
				redirect_to root_path, error: 'У вас на это нет прав'
			end
		end

    def stop_game
      redirect_to root_path
    end

    def player_params
      p_params = params.require(:player).permit(:name, :surname, :login, :vklink, :password, :password_confirmation)
      if p_params[:password].blank?
        p_params.delete("password")
        p_params.delete("password_confirmation")
      end
      p_params
    end

    def player_params_with_avatar
      p_params = params.require(:player).permit(:name, :surname, :login, :vklink, :password, :password_confirmation, :avatar)
      if p_params[:password].blank?
        p_params.delete("password")
        p_params.delete("password_confirmation")
      end
      p_params
    end
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.haml
=render 'shared/flash'
#body
	.row
		.large-12
			%h2 Редактирование входных данных
			=form_for(@player, {multipart: true}) do |f|
				=render 'shared/error_messages', object: f.object

				.row
					.large-8.columns
						=f.label 'Имя'
						=f.text_field :name

						=f.label 'Фамилия'
						=f.text_field :surname

						=f.label 'Логин'
						=f.text_field :login

						=f.label 'Пароль'
						=f.password_field :password

						=f.label 'Подтверждение пароля'
						=f.password_field :password_confirmation

						-if admin_signed_in?
							=f.label "Аватар"
							=f.file_field :avatar
					.large-4.columns
						= image_tag @player.avatar.url(:medium)

				=f.hidden_field :id


				=f.submit 'Ок', class: 'button'

app/views/players/edit_info.haml
=render 'shared/flash'
#body
	.row
		%h2 Редактирование данных вашего профиля
		=form_for @player, multipart: true, html: {method: "patch"} do |f|
			=f.label 'Email'
			=f.text_field :email, type: :email

			=f.label 'Имя'
			=f.text_field :name

			=f.label 'Фамилия'
			=f.text_field :surname

			=f.label 'Ссылка на VK'
			=f.text_field :vklink

			=f.label 'Пароль'
			=f.password_field :password

			=f.label 'Подтверждение пароля'
			=f.password_field :password_confirmation

			- if @player.current_game.present? and @player.current_game.avatar_changeable
				=f.label :avatar, 'Изменить аватар'
				=image_tag @player.avatar.url(:thumb)
				=f.file_field :avatar

			=f.hidden_field :id


			=f.submit 'Ок'

app/views/players/index.haml
.row
	%h1 Список игроков
	=link_to 'Список для печати', print_players_path

.row
	%p
		Живы
		= Player.where(dead:nil).count
		, Мертвы
		= Player.where(dead:'true').count


.row#body(ng-controller='PlayersIndexCtrl')
	-#=foundation_paginate @players
	-#-iter = @players.offset
	%input(type="text" ng-model="query" placeholder="фильтр пользователей")
	%table
		%thead
			%td ID
			%td Аватарка
			%td Имя Фамилия
			%td Жив?
			%td Цель
			%td Всего карточек
			%td Редактировать
		/
			-@players.each do |player|
				%tr
					-#-#%td= iter=iter+1
					-#%td= player.id
					-#%td= link_to player.full_name, player_path(player)
					-#-if !player.dead
					-#	%td Да
					-#	%td
					-#		- if player.target.present?
					-#			= link_to player.target.full_name, player_path(player.target)
					-#		- else
					-#			———
					-#	%td= player.killers_cards.count
					-#
					-#-else
					-#	%td Нет
					-#	%td
					-#	%td
					-#%td= link_to 'Edit player', edit_player_path(player), class: 'tiny button'
					-#%td= link_to 'Delete player',  player_path(player), class: 'tiny button',method: :delete, confirm: 'Are you sure you wanna delete him?'
		%tr(ng-repeat='player in players | orderBy:"id" | filter: query')
			-#%td= iter=iter+1
			%td {{player.id}}
			%td
				%img(ng-src='{{player.avatar_thumb}}')
			%td
				%a(ng-href='/players/{{player.id}}') {{player.full_name}}

			%td(ng-show='player.dead') Убит
			%td(ng-hide='player.dead') Жив
			%td(ng-show='player.target')
				%a(ng-href='/players/{{player.target.id}}') {{player.target.full_name}}
			%td(ng-hide='player.target') —
			%td {{player.killers_cards_count}}
			%td
				%a(ng-href='/players/{{player.id}}/edit' class='tiny button') Edit player
			-#%td
			-#	%a{nghref:'/players/{{player.id}}/edit',class:'tiny button', dataMethod:'delete'} Delete player

=javascript_include_tag('https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js')
:javascript
	var app = angular.module('miptkiller',[])

	app.controller('PlayersIndexCtrl',function($scope){
		$scope.players = #{@players.to_json(only:[:id,:dead],methods:[:full_name,:avatar_thumb,:killers_cards_count],
				include:{target: {only: [:id],methods:[:full_name]}})}
	})

app/views/players/new.haml
.row
	%h1 Регистрация нового игрока

	=form_for @player, multipart: true do |f|
		=f.label :name, 'Имя'
		=f.text_field :name, autofocus: true

		=f.label :surname, 'Фамилия'
		=f.text_field :surname

		=f.label :email, 'E-mail'
		=f.text_field :email, type: :email

		=f.label :email, 'Ссылка на профиль VK'
		=f.text_field :vklink

		=f.label :password, 'Пароль'
		=f.text_field :password, type: :password

		=f.label :password_confirmation, 'Подтверждение пароля'
		=f.text_field :password_confirmation, type: :password

		- if @player.current_game.present? and @player.current_game.avatar_changeable
			=f.label :avatar, 'Изменить аватар'
			=f.file_field :avatar

		=f.submit 'Зарегистрировать', class:'button'

app/views/players/show.haml
=render 'shared/flash'
#body
	.row
		.large-12.columns
			.row
				.large-8.columns
					%h2
						=@player.full_name
					- if @player.current_game.present?
						%h4
							Текущая игра -
							=@player.current_game.name
					- elsif @player.upcoming_game.present?
						%h4
							Игра
							=@player.upcoming_game.name
							начнется
							= l(@player.upcoming_game.starts_at, format: :short)
					- else
						%h4
							У вас нет предстоящих игр.
							= link_to 'Вступайте в игру!', games_path
			
				.large-4.columns
					- if @player.avatar.present?
						= image_tag @player.avatar.url(:medium)
			- if @player.current_game.present?
				.panel
					- if @player.dead
						.alert-box.alert
							Пользователь мертв
					- else
						- if @target.present?
							.row
								.large-2.columns
									=link_to @target.avatar.url(:original), class:'object_block',
									data: {colorbox: true,
									colorbox_height: '95%', colorbox_width: '95%'} do
										=image_tag @target.avatar.url(:thumb)
								.large-10.columns
									%h4
										Цель -
										= @target.full_name

										=form_tag kill_player_path(@target) do
											.small-7.columns
												=text_field_tag 'target[killing_word]', nil, class: 'killing_word', |
													placeholder: 'Killing word' |
												=hidden_field_tag 'target[id]', @target.id
												=hidden_field_tag 'method', 'web'
												=hidden_field_tag 'player[id]', @player.id
											.small-5.columns
												=submit_tag "Убить", class: 'button prefix'




			-if @player.current_game.present?
				%p.killing_word
					Пароль для убийства вас в текущей игре -
					= @player.killing_word

				-unless @player.dead
					%h2 Карточки
					%ul
					-@player.killers_cards.each do |card|
						%li= card.victim.full_name

			%h2 События
			%ul
			-@events.each do |event|
				%li
					= "#{event.source.full_name}"
					=" kills #{event.target.full_name}."
					="Now he has #{event.card_count} cards "
					-if event.new_target.present?
						="and new target - #{event.new_target.full_name}"